name: build-mlp-env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.12
  - numpy=2.3
  - pandas=2.3
  - tabulate=0.9
  - pytorch=2.6.0
  - scikit-learn=1.7
  - matplotlib=3.10
  - jupyter=1.1
  - pip
